### ISSUE TITLE
 HACS Custom Updater

### ISSUE THREAD

**Issue by emouawad** [pnbruckner/ha-illuminance#2]
Unable to add this repository to settings in HACS custom repositories

Repo: https://github.com/pnbruckner/ha-illuminance

HACS UI Error: `Could not add 'pnbruckner/ha-illuminance' with type 'plugin' at this time.
If you used the correct type, check the log for more details.`

Logs:
`2019-08-22 17:10:57 ERROR (MainThread) [hacs.repository.plugin.pnbruckner.ha-illuminance] Repostitory structure not compliant
2019-08-22 17:10:57 ERROR (MainThread) [hacs.api] Validation for pnbruckner/ha-illuminance failed.`

**Comment by pnbruckner** [comment]
I'm tired of trying to keep up with custom_updater and now HACS. If the requirements changed _again_, oh well!

**Comment by emouawad** [comment]
I understand your frustration - thanks again for all the work u did and doing

Not sure that's the case (HACS changed the requirements) but don't know!

Noticed sun2 is working properly with HACS - could it be i am missing something or they are slightly different implementations for HACS?

**Comment by pnbruckner** [comment]
@emouawad Hmm, I think your issue may be simply you chose the wrong type. It should be Integration, not Plugin.

**Comment by emouawad** [comment]
but i tried both of course ;)

**Comment by pnbruckner** [comment]
@emouawad I tried it with the old version of HACS I had installed (0.8.0), as well as the latest & greatest (0.13.2) and I was able to register this repository and install the illuminance custom integration just fine.

**Comment by bbrendon** [comment]
I've been able to install it with HACS no problem.

**Comment by emouawad** [comment]
Thanks guys - done a few updates now it is working properly.
