### ISSUE TITLE
What is the Weather Underground query?

### ISSUE THREAD

**Issue by danodemano** [pnbruckner/ha-illuminance#20]
The link in the documentation:

`https://www.wunderground.com/weather/api/d/docs?d=data/index`

Redirects to:

`https://www.wunderground.com/member/api-keys`

And the example config just says:

`query: !secret wu_query`

So my question is, what is this query that's required? 

Thanks!

**Comment by pnbruckner** [comment]
It's only required when using Weather Underground as the source of weather information. Ignore `query` when using any of the other weather sources. Are you trying to use Weather Underground?

**Comment by danodemano** [comment]
@pnbruckner - thanks for the quick reply! Yes I would like to use Weather Underground.

**Comment by pnbruckner** [comment]
Actually I believe they no longer support their API (since they were bought by IBM back in December 2018.) I haven't used it in a long time. I should probably just remove support for WU.

**Comment by danodemano** [comment]
Ahh gotcha, I've always liked their data. Thanks for the info!
