### ISSUE TITLE
Ramp variation according to weather

### ISSUE THREAD

**Issue by jjmonteiro** [pnbruckner/ha-illuminance#22]
I noticed that it gets darker more rapidly when the weather is bad, than it would when it is sunny.
The sunset ramp always starts one hour earlier, regardless of the weather conditions, and I would argue that in these conditions the ramp should start earlier.

Its now 18:30, its cloudy and its getting dark, the sun will be setting at 20:14.
A real sensor outside is reporting ~1200lx, this sensor reports 7500lx, and will continue until 19:14.

edit: I know its not perfect and it is supposed to be a rough estimation but I just thought this could be an improvement. Its an awesome piece of software, thank you for that.

**Comment by jjmonteiro** [comment]
Allow me to elaborate on this. 

The illuminance variation plotted on a graph follows a parabola shape, having its peak when the sun is directly above our heads, the exact time between the sun rise and the sun set.

Real illuminance sensor plot:
![image](https://user-images.githubusercontent.com/31997649/165493687-b6ab50aa-aa24-4f27-a499-5d57ef8062e8.png)

So according to the current weather, we can determine the peak of the parabola, that is, for example, the maximum luminance we can expect on a cloudy day, then this value can only decay as we approach the sunset.

![image](https://user-images.githubusercontent.com/31997649/165496664-d29b68a8-e790-4180-be0e-8fc29073b108.png)

Of course, if the weather clears meanwhile, the lux levels will go up, but they can only go as far as allowed for that particular time of the day (as we can see on the real graph around 16h).

Only three points are needed to define a parabola, and it can easily be represented by its standard formula "y=ax^2+bx+c"

p1) We know the sun rise time and initial lux level
p2) We know the sun set time and the final lux level
p3) We can estimate the maximum possible lux level according to current weather

So we can derive a mathematical function that will output the expected lux level at a particular time of the day!

Here's my attempt at putting this into python code:

    import datetime

    # @param  now_s  Current time in seconds
    # @param  s_rise Sun rise time in seconds
    # @param  s_set  Sun set time in seconds
    # @param  min_lx Minimun allowed lux level
    # @param  max_lx Maximum allowed lux level (current weather max estimated lux)
    # @return Current lux level

    def get_current_lux(now_s, s_rise, s_set, min_lx, max_lx):

        mid_day = (s_rise / 2) + (s_set / 2)
        A1 = -mid_day ** 2 + s_rise ** 2
        B1 = -mid_day + s_rise
        D1 = -max_lx + min_lx
        A2 = -s_rise ** 2 + s_set ** 2
        B2 = -s_rise + s_set
        D2 = -min_lx + min_lx
        BM = -(B2 / B1)
        A3 = BM * A1 + A2
        D3 = BM * D1 + D2
    
        a = float(D3) / A3
        b = ((D1 - A1 * a) / B1)
        c = (max_lx - (a * mid_day ** 2) - (b * mid_day))
    
        if s_rise <= now_s <= s_set:
            result = a * now_s ** 2 + b * now_s + c
        else:
            result = min_lx
        return int(result)

    now = datetime.datetime.now()
    midnight = datetime.datetime.combine(now.date(), datetime.time())
    now_seconds = (now - midnight).seconds

    sun_rise_seconds = 20460
    sun_set_seconds = 72840
    min_lux = 10
    estimated_max_lux = 4400

    print(get_current_lux(now_seconds, sun_rise_seconds , sun_set_seconds , min_lux, estimated_max_lux ))

**Comment by pnbruckner** [comment]
@jjmonteiro thanks for your suggestion and very useful supporting data!

As a bit of background, the algorithm used in the current implementation came from the SmartThings platform I had used before HA, and was implemented by someone else. I have no idea where that person got the idea/algorithm. But I found it useful then, and when I first started using HA, since I didn't have a real light sensor at the time. I don't actually use this anymore (since I _do_ now have light sensors), I just maintain it since other people have found it useful.

What you're suggesting sounds even more useful. I'm a bit busy right now (I enhanced my "sun2" custom integration, but have yet to release it, and I'm working on updating the life360 integration from the old "legacy" format to the new entity-based format), but I'd like to incorporate this when I have time. I'll probably do so by making it an option, since I don't necessarily want to change the behavior for current users without giving them a choice.

Thanks again! Hopefully I'll get to this before long.

**Comment by pnbruckner** [comment]
So I did a bit of searching for estimating the sun's illuminance throughout the day, how to express that curve mathematically, etc., and ran across a publication from the US Naval Observatory from 1987 entitled "Computer Programs for Sun and Moon Illuminance With Contingent Tables and Diagrams." It was on Google Play Books and was a scanned copy from the University of Illinois. What a coincident -- I graduated from there in 1982! 😆 

Anyway, it included a program written in FORTRAN and BASIC, but I was able to find the important part that estimated the sun's illuminance starting with its altitude, aka elevation. I converted that to Python and ran a quick test program to calculate values for today's illuminance starting an hour before sunrise to an hour after sunset (and, of course, using my location.) The result looks like this:

![image](https://user-images.githubusercontent.com/36015321/167277344-64edc066-29a9-4d6e-b210-7e510870a3eb.png)

The equations are fairly simple so I should be able to use that in this sensor. I'll get started on it hopefully in the next couple of weeks.

**Comment by pnbruckner** [comment]
By the way, it included the ability to specify a value to divide the result by to account for weather. This is what it suggested:

![image](https://user-images.githubusercontent.com/36015321/167277657-1ca02ba1-c908-4ba1-b85d-520b02cb7496.png)

I'll try to that that into account, too - i.e., maybe adjust the values I've been using for the various weather conditions.

**Comment by pnbruckner** [comment]
FWIW, here's what the new curve looks like compared to the old one:

![Screenshot from 2022-05-17 21-29-01](https://user-images.githubusercontent.com/36015321/168944970-e80d5dbd-fcdf-45cd-a5c5-6daed3fdc60d.png)

I've still been busy with other things, but hopefully will have something before long.

**Comment by jjmonteiro** [comment]
wow looks awesome!
