### ISSUE TITLE
Use Accuweather Cloud Cover %

### ISSUE THREAD

**Issue by Madelena** [pnbruckner/ha-illuminance#25]
The Accuweather HA integration also provides a Cloud Cover % value. Using that should result in a more accurate graph instead of mapping the current conditions.

Thanks for the awesome integration!

**Comment by pnbruckner** [comment]
True. Dark sky can provide that, too, and I'm sure others do as well. I'll look into how to make that an option.

**Comment by julienld** [comment]
OpenWeatherMap also provide the cloud coverage (sensor.openweathermap_cloud_coverage). I think this could be more accurate than mapping the current condition and output less "jumps" in the illuminance.
