### ISSUE TITLE
Feature Request: fallback when weather sensor fails

### ISSUE THREAD

**Issue by rigrig** [pnbruckner/ha-illuminance#27]
The last Home Assistant update [broke OpenWeatherMap](https://github.com/home-assistant/core/issues/74527), resulting in the illuminance sensor returning `unknown`, (log: `No attribution attribute: weather.openweathermap`.)    
My automations expect a numeric value (to prevent flickering the lights when illuminance is `unknown` during HA restart), so didn't turn on my lights when it got dark.

Maybe instead of bailing out when it can't find/handle current conditions, the illuminance sensor could just fall back to ignoring the weather sensor, so lights at least still turn on/off according to day/night?

**Comment by pnbruckner** [comment]
Good idea. In fact, I can even make using a weather entity optional, which would just give the curve based solely on sun position.

**Comment by pnbruckner** [comment]
@luberk8, no, not yet. In theory the "fallback" feature could do it, but the current implementation expects to see the weather entity at least once, and until it does, the sensor's state will be "unknown". I've been meaning to change that, but I could also explicitly make the weather entity optional. I kind of have that on my "to do" list, just haven't gotten around to it. I'll try to do it sooner rather than later.

**Comment by rrooggiieerr** [comment]
> give the curve based solely on sun position

I would be very interested in this option but understand this is not yet implemented as weather data source is stil a required argument. Any plans to implement this?

**Comment by pnbruckner** [comment]
Yes, but with all the work I recently did on the Life360 integration, which is now broken, yet again, this kind of got pushed to the "back burner." I'll try to do this soon.

**Comment by pnbruckner** [comment]
@rigrig, @luberk8, @rrooggiieerr, I just released 5.5.0b0 that makes the weather entity optional. It hopefully also handles the case of a "bad" weather entity at startup better, but that's yet to be seen. If you give the beta a try, let me know how it works for you.

**Comment by pnbruckner** [comment]
Fully released fix in 5.6.0.
