### ISSUE TITLE
Support for SMHI

### ISSUE THREAD

**Issue by jef74** [pnbruckner/ha-illuminance#28]
Hi,

Would it be possible to add support for SMHI service?

https://www.home-assistant.io/integrations/smhi

**Comment by pnbruckner** [comment]
Looks like it would be relatively straightforward, but I don't think I could test it.

**Comment by pnbruckner** [comment]
There was a suggestion for using a single condition mapping table that should work for all weather integrations that use the standard list of conditions, which I believe this one does. I'll probably implement that suggestion soon.
