### ISSUE TITLE
Illuminance Forecast

### ISSUE THREAD

**Issue by Madelena** [pnbruckner/ha-illuminance#32]
Since the sensor is a calculated value, would it be possible to provide the forecast of illuminance in the next 12 hours, if the forecast data is provided? 

For example, the Accuweather API (not the Accuweather HA integration) provides 12 hours of cloud cover forecast:

![image](https://user-images.githubusercontent.com/4341881/211422202-96803afd-2163-4610-a492-8410f17157b8.png)

So I can plot fun charts like this:

![image](https://user-images.githubusercontent.com/4341881/211422266-fd34cb24-da50-448f-94d7-73109ece7917.png)

Would be nice if I can feed the data into this integration and get what the illuminance is like for the next 12 hours. I can make automations that preemptively turn on lights in anticipation of darker skies, or it's useful simply for checking if I need to wear a hat.

**Comment by pnbruckner** [comment]
This is an interesting idea, but if there aren't any standard integrations (or even custom integrations) that provide cloud coverage forecast in a consistent manner, I'm not sure this would get much use.
