### ISSUE TITLE
Error in homeassistant 2023.4

### ISSUE THREAD

**Issue by sjobergsson** [pnbruckner/ha-illuminance#42]
After updating to homeassistant 2023.4.0 I get this error "Platform error sensor.illuminance - No module named 'homeassistant.components.darksky'"
The configuration i have is
- platform: illuminance
  entity_id: weather.home
Where weather.home is a met.no weather entity.

**Comment by Langelus** [comment]
Can confirm, seeing the same error.

**Comment by Langelus** [comment]
@sjobergsson Update the integration in HACS, seems like 4.0.1 has already fixed this.

**Comment by sjobergsson** [comment]
Seems like it , restarting homeassistant after the installation now and then I will try that but sounds promising :)

**Comment by sjobergsson** [comment]
Yes 4.0.1 works again :)
