### ISSUE TITLE
Constant curve, not taking info on the weather conditions

### ISSUE THREAD

**Issue by AseKarlsson** [pnbruckner/ha-illuminance#45]
Hi,
My graph is constant every day dispite changes in weather conditions.

![image](https://user-images.githubusercontent.com/80900477/233793260-42ff0854-7e4f-4a60-8438-df33dcc8f240.png)

I have Met.no installed.

Code:
```
  - platform: illuminance
    name: Outdoor Illuminance
    entity_id: weather.forecast_home
```
EntityID above is the Mee.no entity
Have I missed something in the configuration?

**Comment by AseKarlsson** [comment]
Also tried:
[OpenWeatherMap](https://www.home-assistant.io/integrations/openweathermap/)

It did give theese entities:
sensor.owm_pollution_ammonia_nh3
sensor.owm_pollution_carbon_monoxide_co
sensor.owm_pollution_coarse_particles_pm10
sensor.owm_pollution_fine_particles_pm2_5
sensor.owm_pollution_nitrogen_dioxide_no2
sensor.owm_pollution_nitrogen_monoxide_no
sensor.owm_pollution_overall_air_quality
sensor.owm_pollution_ozone_o3
sensor.owm_pollution_sulphur_dioxide_so2
sensor.owm_ultraviolet_index
sensor.owm_pollution_forecast

But could not find theese useful.

Any advice?

//Ase

**Comment by pnbruckner** [comment]
What is your current Illuminance configuration? What is the Entity ID of the weather entity you're trying to use as an input to the illuminance integration? Have you confirmed under Developer Tools -> STATES that you have the weather entity's Entity ID correct?

For OpenWeatherMap, you can either use the weather entity (e.g., `weather.owm'), or the sensor that indicates condition (e.g., `sensor.owm_condition`), or the sensor that indicates cloud coverage percentage (e.g., `sensor.owm_cloud_coverage`.) If you don't see these entities, you may need to go to the Entities page to enable them.

**Comment by AseKarlsson** [comment]
Solved!
Found a typo even efter multiple earlier checks. Now the graph starts to look different.
Thanks,
Ase
