### ISSUE TITLE
No state history found

### ISSUE THREAD

**Issue by dkovacic74** [pnbruckner/ha-illuminance#47]
After I upgraded HA core to 2023.8.4 and HA OS to 10.5 estimated illuminance stopped with "no state history found" error message.

What is the cause?

**Comment by pnbruckner** [comment]
I just tried it with the latest HA dev release and it seems to work ok. Can you share your config? Are there any associated errors or warnings in the log? Can you enable debug for this integration, restart HA and see if there are any associated debug messages in the log?

**Comment by dkovacic74** [comment]
This is my configuration:

  - platform: illuminance
    name: Estimated Illuminance
    entity_id: weather.dudo_s_home


This is error log I have:

This error originated from a custom integration.

Logger: custom_components.illuminance.sensor
Source: custom_components/illuminance/sensor.py:238 
Integration: illuminance (documentation, issues) 
First occurred: 1:14:25 PM (1 occurrences) 
Last logged: 1:14:25 PM

Estimated Illuminance: Unsupported sensor: weather.dudo_s_home, attribution: Weather forecast from met.no, delivered by the Norwegian Meteorological Institute.

**Comment by pnbruckner** [comment]
What version of this custom integration are you using? Doesn't look like the latest.

**Comment by dkovacic74** [comment]
I have 3.0.0 but I cannot uodate it through HACS update

**Comment by pnbruckner** [comment]
What is preventing you from upgrading? You just say you can't with no details as to why.

**Comment by dkovacic74** [comment]
When I try to update via HACS, I get following response. But I updated manually, and it works.![image](https://github.com/pnbruckner/ha-illuminance/assets/46868612/7399fefb-eddc-46b4-b610-6dbd8bf324d2)

**Comment by pnbruckner** [comment]
Great, HACS is at it again, adding new requirements. Will it ever stop?!

Well, not sure if I'll be able to keep with the ever-moving target of HACS, but at least you were able to upgrade this custom component and it's working for you. I'll close this issue. Feel free to reopen, or open a new one, if necessary.

**Comment by dkovacic74** [comment]
Ok, that's fine!
