### ISSUE TITLE
Add support for the Climacell API/Custom Component

### ISSUE THREAD

**Issue by ajayjohn** [pnbruckner/ha-illuminance#5]
If possible, could you please update this component to use the data provided by the Climacell service (https://github.com/r-renato/ha-climacell-weather 2), now that Dark Sky is on its way out?

I really like what you have created here and wish I would be able to use it even after Dark Sky is removed from my instance.

**Comment by 89jd** [comment]
Agreed, would be great to get this

**Comment by pnbruckner** [comment]
I'd rather not add support for custom integrations, especially since there are enough standard, free weather integrations already supported.
