### ISSUE TITLE
Question / Feature Request regarding scan interval

### ISSUE THREAD

**Issue by hgregorian** [pnbruckner/ha-illuminance#55]
Hello, first off, thanks for this custom integration!  It's been really useful to me in having better control over my landscape lights without possessing an outdoor luminosity sensor.

With that said, my automations could be more precise if the scan interval could be lower.  Is there a technical reason why the minimum is 5 minutes?  I'd appreciate being able to lower my scan interval to 1 minute.

**Comment by pnbruckner** [comment]
That probably was because when I first created this it directly queried the weather underground server, which, of course, it no longer does. I'll look into it, but it might not be until after the holidays.

**Comment by hgregorian** [comment]
Great, thank you!  For now, I've modified const.py on my instance.

> That probably was because when I first created this it directly queried the weather underground server, which, of course, it no longer does. I'll look into it, but it might not be until after the holidays.
