### ISSUE TITLE
Values sometimes jump around wildly

### ISSUE THREAD

**Issue by iridris** [pnbruckner/ha-illuminance#64]
Occasionally I'll get values that swing wildly. Not sure if this is due to specific weather conditions, temporary glitches in weather data, or what.

Example:
![image](https://github.com/pnbruckner/ha-illuminance/assets/952387/a306f490-0cab-45bc-a353-cb8c1c3b8ecc)
Zoomed in on that big drop:
![image](https://github.com/pnbruckner/ha-illuminance/assets/952387/3e948783-1a42-4a17-82eb-a7531bf0457d)

Other days can jump around even more:
![image](https://github.com/pnbruckner/ha-illuminance/assets/952387/4f14e75e-84e1-455e-b3d3-e547abdc3541)

My configuration options:
![image](https://github.com/pnbruckner/ha-illuminance/assets/952387/d5070e98-dd40-443a-a2f9-a7ce395c8396)

Would this be expected behavior?

**Comment by pnbruckner** [comment]
That is completely normal when using a weather entity that only provides a weather "condition." If you want results with more precision, then use a "cloud percentage" sensor.

**Comment by iridris** [comment]
Thanks!! I've switched it to the cloud coverage sensor and will monitor to see if the values smooth out.

**Comment by iridris** [comment]
I'm still seeing a lot of jumpy values - but I think it is due to the source data - not an issue with Illuminance. I'll go ahead and close this. Thanks for the help pnbruckner!
![image](https://github.com/pnbruckner/ha-illuminance/assets/952387/4323a96f-8362-4cd9-aed0-38537d1f0d56)
![image](https://github.com/pnbruckner/ha-illuminance/assets/952387/2efb0cc3-ace5-4547-b31b-d567accde215)

**Comment by pnbruckner** [comment]
FWIW, I have tested now for a bit with two different cloud coverage sensors. The one from OpenWeatherMap we've been discussing, and one I created with a Template Helper using an attribute of the Met.no climate entity (`{{ state_attr('weather.forecast_home', 'cloud_coverage') }}`). The latter can still be a bit jumpy, but it does seem to produce more distinct values that the OpenWeatherMap one. I.e., the OWM one seems to use only four values, whereas the Met.no one uses a lot more values for a (sometimes) smoother curve. You might want to give that a try.

**Comment by pnbruckner** [comment]
FYI, here is the illuminance as seen by a sensor on the front of my house:

![image](https://github.com/pnbruckner/ha-illuminance/assets/36015321/8925ad81-d42c-468d-b56a-984bda95e472)

And here is what the two Illuminance sensors estimated based on the two different could coverage sensors over the same period:

![image](https://github.com/pnbruckner/ha-illuminance/assets/36015321/838870b2-7d95-4a70-af10-072ddabd9b85)

Neither are a perfect estimate, but they both do reasonably well. Actually, although I haven't tried it, an average of the two might be even better. (I suppose either one Illuminance sensor with an average of the cloud sensors as input, or an average of two Illuminance sensors, each using one of the two cloud sensors. Not sure which would be better, or if it would make a difference.)
