### ISSUE TITLE
Many error messages

### ISSUE THREAD

**Issue by mikezieg** [pnbruckner/ha-illuminance#65]
I found many error messages like this in my log file:
2024-04-22 06:14:13.000 ERROR (MainThread) [custom_components.illuminance.sensor] Illuminance met.no: Cloud coverage sensor state is not a number between 0 and 100: 138
There are more than 1000 lines like this - per second!
That doesn't just happen with met.no but also with other weather-integrations. The coverage sensors seems to give values above 100 especally at night.

**Comment by mikezieg** [comment]
>Have you created a template sensor from that which you then use as an input to the Illuminance integration?
Yes. 
I have tried various weather integrations and this one generally seemed good to me because it provides a lot of information. But Astroweather has the same problem. Maybe the value has a different meaning at night?
But I also don't understand why there are so many error messages. It seems to me that this puts quite a lot of stress on the system.

**Comment by pnbruckner** [comment]
> But I also don't understand why there are so many error messages. It seems to me that this puts quite a lot of stress on the system.

Because I never expected something to generate a cloud coverage percentage value above 100%. I expected bad values to come from a bad sensor, and the user would stop using it.

**Comment by pnbruckner** [comment]
@mikezieg let me know if 5.4.3 solves the problem for you.

**Comment by pnbruckner** [comment]
Looking back on what you said a couple of times, I understand why the error occurred, but I guess I didn't catch the fact that you said, "There are more than 1000 lines like this - _per second!_" I can't understand how that could happen.

I.e., the sensor only updates once every 5 minutes (by default), or whenever the input entity (in this case, the cloud coverage sensor) updates. The periodic update frequency can be changed, but the minimum period is 30 seconds. So, if there were 1000's of errors per second, the only way I can see that could happen is if the cloud coverage sensor was updating that fast.

**Comment by mikezieg** [comment]
Great, there are no more entries in the error log.
I can't say why there were so many before.
In any case, thank you again for the quick fix.
