### ISSUE TITLE
Add more Integrations

### ISSUE THREAD

**Issue by duczz** [pnbruckner/ha-illuminance#67]
Hey can you add more weather integrations / Supported weather sources?

DWD - https://github.com/FL550/dwd_weather
![image](https://github.com/pnbruckner/ha-illuminance/assets/25475385/96c68ca2-7687-48cf-b2e4-421e6c5f4495)

Weather.com - https://github.com/jaydeethree/Home-Assistant-weatherdotcom
![image](https://github.com/pnbruckner/ha-illuminance/assets/25475385/4183526b-f10e-4605-a09b-aeb66c31d95b)

**Comment by gadric** [comment]
I can confirm that DWD weather integration works

**Comment by duczz** [comment]
Your right works now, strange
