### ISSUE TITLE
Add Deutscher Wetterdienst as supportet

### ISSUE THREAD

**Issue by dennisvandehoef** [pnbruckner/ha-illuminance#68]
Heey,

thanks for this great integration.
I am using it successfully with weather information from https://github.com/FL550/dwd_weather, so this  "issue" is my way of letting you know that you can add them to the list of supported weather sources.

**Comment by FaserF** [comment]
Hi, I added support for it with my fork: 
https://github.com/FaserF/dwd-illuminance

Unfortunatly @pnbruckner  does not want custom weather integrations to be supported here, therefore my PR has been rejected: https://github.com/pnbruckner/ha-illuminance/pull/17

**Comment by jf-64** [comment]
> Glad to hear, that it now works without any custom changes needed

I think, if it would really work with DWD, it would be listed in the list of [Supported weather sources](https://github.com/pnbruckner/ha-illuminance?tab=readme-ov-file#supported-weather-sources).

**Comment by pnbruckner** [comment]
> Unfortunatly @pnbruckner does not want custom weather integrations to be supported here, therefore my PR has been rejected: #17

Before I changed the integration to support standard mappings, I didn't want to continually add mappings for new weather integrations, especially ones I couldn't test myself. But now that it doesn't require individual mappings for every weather integration, it hopefully works with many of them.

> I think, if it would really work with DWD, it would be listed in the list of [Supported weather sources](https://github.com/pnbruckner/ha-illuminance?tab=readme-ov-file#supported-weather-sources), even if it is supporting the "standard" sources...

That is really only a list of weather integrations I've been able to test myself, with hints as to which entity or entities to use. But since this works with many different integrations, and the requirements for those are fairly straightforward, I should probably just remove that list from the documentation.

**Comment by jf-64** [comment]
Just for the records: 
Here is the visualized data side by side for my city (Nuremberg) for today: 

- on the top the "official" Sun irradiance by DWD,
- on the bottom your calculations by Met.no and Oper Weather Map.

![image](https://github.com/user-attachments/assets/c76696b2-2739-4f66-a4bf-116ea746b6cb)

**Comment by pnbruckner** [comment]
> my city (Nuremberg)

I was there once, a long time ago, back in the 1980's. It was very nice, as I recall. Here's a little memento I have from my visit:

![20241008_144742](https://github.com/user-attachments/assets/9e8d7f8b-229e-412f-8302-7c217cba034d)

😃

**Comment by jf-64** [comment]
At that time I still lived in other places...

Here are the curves for today:
![image](https://github.com/user-attachments/assets/0c7a68c2-8a36-4a55-9dfe-0ce6d98f99de)

Now I included also the calculation by DWD (for the DWD data). Thus, they can be better compared:

1. The scale seems to be correct (today) - mostly with OWM and mostly until early afternoon.
2. In the afternoon and evening your algorithm seems to be unable to reproduce the data properly.
3. You get partly the same output data from different input data (sources).
4. Interestingly, the calculation using the data from the DWD service does not come any closer to the original DWD data.
5. It seems, the cloud coverage is disproportionately taken into account. (I'm pretty sure, the data by OWM isn't 100% correct. The data from X is much finer grained, but still results in rough zigzag curves.)

Here is the cloud coverage by DWD and OWM for the same time frame:
![image](https://github.com/user-attachments/assets/9b929fff-905e-42ed-aa06-cddf4ab3754c)

**Comment by jf-64** [comment]
> The illuminance or irradiance without weather data should be pretty accurate. 

If you check out the data of yesterday, the accuracy is pretty rough. But you're right, for light switches it still shall be fine.
