### ISSUE TITLE
Add support for Weatherbit

### ISSUE THREAD

**Issue by lubbertkramer** [pnbruckner/ha-illuminance#7]
Because Darksky will be removed from Home Assistant it's great to have a working alternative for your work that is used by me and a lot of other users

One of the community replacements is Weatherbit:

https://community.home-assistant.io/t/weatherbit-io-current-weather-and-forecast-data/200224
https://github.com/briis/weatherbit

**Comment by pnbruckner** [comment]
I'd rather not add support for custom integrations, especially since there are enough standard, free weather integrations already supported.
