### ISSUE TITLE
Cloud Coverage from forecast

### ISSUE THREAD

**Issue by wigster** [pnbruckner/ha-illuminance#70]
Hi

I am using the weather.com (HACS) integration for my weather forecast. For whatever reason, the API does not provide current cloud coverage as a numerical sensor, (just a description). However, in the forecast the cloud_coverage key is there properly as a fraction.

Would it be possible to get Illuminance to pull the cloud coverage from the first forecast key as a proxy if the quantity is not available in the current conditions?

**Comment by pnbruckner** [comment]
Create a template sensor. That's what I do.

**Comment by pnbruckner** [comment]
To be clear, I mean to create a template sensor that gets the cloud coverage percentage from the weather.com entity, and then use the template sensor as the input to this integration.
