### ISSUE TITLE
Feature request: Consider window direction

### ISSUE THREAD

**Issue by henryk** [pnbruckner/ha-illuminance#71]
I don't know the underlying Naval Observatory formula, but how hard would it be to include the direction (and maybe relative size) of the windows in the calculation?

Here's an example of a room that has a relatively narrow east-facing window (top graph is actual measurement, bottom graph is ha-illuminance):

![image](https://github.com/user-attachments/assets/5666860a-571c-428f-9722-13a901c7c1bf)

The beginning and end of the sensor measurement shows variations because of people moving in front of the sensor and opening/closing curtains (which is one of the reasons why I don't think this sensor is useful for automatic actions). But you can clearly see that the actual brightness reaching the room follows a different curve.

**Comment by Jpsy** [comment]
I strongly support this request. Actually I also started some research some time ago about how to calculate the illumination through a window. But this is not trivial. There are more factors to take into account here:

1. Current elevation and azimuth of the sun (already known in this integration) 
2. Cloud coverage (already known in this integration)
3. Amount, direction and angular spread of direct, diffuse and ambient sun light. We need some function to determine how direct sun light decreases into ambient light with growing angle from the line of sight to the sun and with cloud coverage.
4. Window size
5. Window transparency
6. Window direction and also window tilt angle (for roof windows). This determines the incident angle between the sun's rays and the normal to the window plane. It influences how much light enters and how much is reflected out.
7. Math to join all the above factors into a total illuminance through the window. 
8. Unfortunately there could also be outside surfaces that reflect light back in, like neighboring houses. This makes moddeling and calculation really difficult, but could also be ignored or simulated by additional windows in other directions.

Topics 3, 7 and 8 require research to determine the needed algorithms or some good approximations. This is where the OP can do some work himself and I would also be willing to help.

It should also be clear, that it does not suffice to calculate just one window. Rooms may have multiple windows with different sizes, directions and tilt angles. Any good solution should be able to create an arbitrary number of sensors, one for each window. The user could then create a HA template sensor to add them up. Or the integration itself must provide room sensors that add up over multiple window sensors. 

All in all this is not a simple feature request.
I suggest that it should all start with Phil @pnbruckner and/or the contributers giving some feedback whether they see a chance to do the implementation. Then the OP and me could start to dig into the algorithms and try to provide and discuss the math here.

@henryk  would you be willing and able to do that part of the work (together with me), if Phil gives a green light?

**Comment by pnbruckner** [comment]
Honestly, this sound way too complicated, would be a huge undertaking to implement, and I doubt it would get enough use to make it worthwhile. But, if this is something you could see making work for yourself, and you think this integration is a good basis, by all means, feel free to fork the project. I just don't see myself working on a feature like that. But thanks for the suggestions anyway!

**Comment by Jpsy** [comment]
Wow, really completed? Or just closed?

**Comment by pnbruckner** [comment]
Just closed. As explained above, it's not something I plan to do.
