### ISSUE TITLE
Suggestion: Heuristics should (optionally) take precipitation into consideration

### ISSUE THREAD

**Issue by magicus** [pnbruckner/ha-illuminance#75]
The current heuristics does a good job of adjusting the illumination based on the cloud coverage, but it is insufficient. At least here in Sweden during the dark season, it is clear that the amount of daylight differs vastly between days, even if the cloud coverage is 100% all time. When it is raining, the clouds are generally much thicker (and grayer/darker), and block more light.

I believe the "cloud coverage" metrics from the weather services measures how large portion of the sky that is covered with clouds, but not how *thick* those clouds is. So a thin layer of stratospheric clouds would not block much sunlight, but will still be considered 100% if there is no visible sky.

It would be great if we could optionally also feed in a precipitation sensor into the integration. If this is > 0, then it should scale up the "dampening effect" of the cloud cover, possibly somewhat related to the amount of precipation. (With a lot of heavy raining it feels much darker, than a light shower.)

I realize this is not an exact science, and might need some tweaking to get it right, but I guess the same goes for the cloud cover calculations.

If you are interested in accepting PRs, I might try to do something about this, unless someone else beats me to it.

**Comment by magicus** [comment]
I understand that, and I use it the same way. I have light sensors but they are unfortunately not very sensitive in the range where it matters; the fine levels of going from almost-dusk to definitely-dusk are easy to spot with your eye but hard to get a reading on. So the output from this integration has been much more reliable to determine when to turn on the lights.

I've solved this partially by converting the output from this integration to a logarithmic scale -- I did not find any existing such unit, so I designed my own and called it pLux. This makes high light levels compressed and low light levels more spaced out. I've found a pretty good value for what pLux value my lights should go on at. (I've actually tracked that by a notification on my phone for almost a year, checking that the light level seems right.) I've been pondering about submitting a PR that would add this logarithmic scale to this integration, or making a Blueprint out of it, but it just has not happened...

**Comment by pnbruckner** [comment]
> I have light sensors but they are unfortunately not very sensitive in the range where it matters; the fine levels of going from almost-dusk to definitely-dusk are easy to spot with your eye but hard to get a reading on.

I have two Z-Wave sensors. a Zooz ZSE40, and an Aeotec ZW100. I started with the former, but it tops out at 50 lux, so then I got the latter which reads a much wider range (up to 30,000 lux.) I ended up using the ZWE100 outside, and the ZSE40 inside, due to that, as well as other reasons (e.g., the ZSE40 is battery only, whereas the ZW100 can run off a power supply.)

But, for your purposes, maybe something like the ZSE40 might work better, since it concentrates on the low light levels. (Although it's not really meant for outside, if you use a power supply, it might work.)

> I've solved this partially by converting the output from this integration to a logarithmic scale

I'm not sure how that can help. Can't you just use more precise values for thresholds? The graph might look better, but I'm not really sure it's helping with automation.

**Comment by magicus** [comment]
> I'm not sure how that can help. Can't you just use more precise values for thresholds? 

Sure, it was not so much a technical enabler as a usability thing. It was just sooo much easier to fine-tune the value, to find the sweet spot where to turn on the light. 

The difference is between finding the sweet spot between 15 and 20 lux in this graph:

<img width="1232" alt="Screenshot 2024-12-20 at 14 43 15" src="https://github.com/user-attachments/assets/309ad377-5261-4e5f-acac-de7583001523" />

or finding the value between 10 and 15 in this graph: (My current cutoff is at 12)
<img width="1232" alt="Screenshot 2024-12-20 at 14 47 18" src="https://github.com/user-attachments/assets/0880b887-49fb-4a72-80c0-ff6e593fee9d" />

By 9 o clock it is basically daylight, and dawn is over. In the latter graph, you can clearly see how dawn progresses from the first visible light at around 8 o clock. In the former, it looks like the difference between 8 and 9 is minimal, and everything of importance happens between 9 and 12. But that is not how the human eye perceives it; instead the dramatic shift in light happens the first hour after sunrise, and then it is "daylight" all through the day.

I'm also using the "pLux" value to show a gauge meter telling me the amount of "daylight" outside. (Not very useful, but kind of entertaining...) It really matches very well with the perceived amount of light.

**Comment by magicus** [comment]
In the summer, the peak lux value goes up one or two magnitudes, but that only means it raises like 10 or 20 on the pLux scale. Once again, that "feels" more right; a winter day does not seem like it is just 1% of the brightness of a summer day, but perhaps like 2/3 or half the brightness or so. So going from 30 at a winter day to 50 at a summer day feels like it captures something "real".
