### ISSUE TITLE
Add support for your own illumaniance sensor

### ISSUE THREAD

**Issue by lubbertkramer** [pnbruckner/ha-illuminance#8]
Because Darksky will be removed it's good to have a working alternative. On of the ideas that could be done is giving users the choice of determing their own illuminance sensor. Make this in a predefined template sensor that is used by the HA-Illuminance sensor or just use the illuminance from one of the device below

For example:
Own weatherstation like weatherflow - https://github.com/briis/smartweather
Xiaomi light sensor - https://nl.aliexpress.com/item/4000475208359.html?spm=a2g0s.9042311.0.0.27424c4d6xJq8U
Xiaomi motion sensor - https://www.aliexpress.com/snapshot/0.html?spm=a2g0s.9042311.0.0.27424c4dfukaxi&orderId=900277006434090&productId=32975225751

**Comment by pnbruckner** [comment]
Thanks for the suggestion, but I think there are enough standard, free weather sensors available that are already supported.
